### ISSUE TITLE
`sv` fails to parse data type with 18 fields but can parse data type with 17 fields

### ISSUE THREAD

**Issue by ChShersh** [qfpl/sv#26] opened 2018-11-22 06:23 UTC
I have not so small data type and I have named CSV encoder and decoder for this data type. I've also implemented property-based roundtrip tests to check whether my decoders and encoders correct. Unfortunately tests fail in one case out of ten thousands for some specific data type sample. And I can't figure out what's wrong with my decoder.

I can reproduce the error on the CSV below, see the full code:

```haskell
#! /usr/bin/env cabal
{- cabal:
build-depends: base >= 4.9 && < 4.13
             , bytestring
             , sv == 1.2
             , text >= 1.2.3
-}

{-# LANGUAGE ApplicativeDo     #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards   #-}

module Main where

import Data.ByteString (ByteString)
import Data.Sv (Encode, NameDecode', NameEncode, defaultParseOptions, parseDecodeNamed)
import Data.Sv.Decode (Decode', double, int, orEmpty, utf8, (.:))
import Data.Sv.Encode ((=:))
import Data.Text (Text)

import qualified Data.ByteString.Lazy.Char8 as LBS8

data User = User
    { user_id           :: Int
    , group_id          :: Text
    , arm               :: Int
    , first_name        :: Text
    , last_name         :: Text
    , email             :: Text
    , contact_number    :: Text
    , start_date        :: Text
    , status            :: Text
    , dose_smart_id     :: Maybe Text
    , fitbit_id         :: Maybe Text
    , glyco_id          :: Maybe Text
    , sms_reminder      :: Text
    , email_reminder    :: Text
    , inactive_reminder :: Text
    , starting_weight   :: Double
    , starting_bmi      :: Double
    , starting_hba1c    :: Double
    } deriving (Show)

userDecoder :: NameDecode' ByteString User
userDecoder = do
    user_id           <- "id"                .: int
    group_id          <- "group_id"          .: utf8
    arm               <- "arm"               .: int
    first_name        <- "first_name"        .: utf8
    last_name         <- "last_name"         .: utf8
    email             <- "email"             .: utf8
    contact_number    <- "contact_number"    .: utf8
    start_date        <- "start_date"        .: utf8
    status            <- "status"            .: utf8
    dose_smart_id     <- "dose_smart_id"     .: orEmpty utf8
    fitbit_id         <- "fitbit_id"         .: orEmpty utf8
    glyco_id          <- "glyco_id"          .: orEmpty utf8
    sms_reminder      <- "sms_reminder"      .: utf8
    email_reminder    <- "email_reminder"    .: utf8
    inactive_reminder <- "inactive_reminder" .: utf8
    starting_weight   <- "starting_weight"   .: double
    starting_bmi      <- "starting_bmi"      .: double
    starting_hba1c    <- "starting_hba1c"    .: double
    pure User{..}

testUser :: User
testUser = User
    { user_id = 10
    , group_id = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    , arm = 1
    , first_name = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    , last_name =
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    , email = "aaaaaaa"
    , contact_number = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    , start_date = "2018-01-01 00:00:00 UTC"
    , status = "Active"
    , dose_smart_id = Nothing
    , fitbit_id = Nothing
    , glyco_id = Nothing
    , sms_reminder = "Never"
    , email_reminder = "Weekly"
    , inactive_reminder = "Never"
    , starting_weight = 100.01
    , starting_bmi = 10.01
    , starting_hba1c = 1.0e-2
    }

-- CSV representation of testUser
userCsv :: LBS8.ByteString
userCsv = LBS8.intercalate "\n"
  [ "id,group_id,arm,first_name,last_name,email,contact_number,start_date,status,dose_smart_id,fitbit_id,glyco_id,sms_reminder,email_reminder,inactive_reminder,starting_weight,starting_bmi,starting_hba1c"
  , "10,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,1,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,aaaaaaa,aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,2018-01-01 00:00:00 UTC,Active,,,,Never,Weekly,Never,100.01,10.01,1.0e-2"
  ]

main :: IO ()
main = print $ parseDecodeNamed userDecoder defaultParseOptions userCsv
```

And the error I see:

```haskell
Failure (DecodeErrors (UnexpectedEndOfRow :| []))
```

I've tried to make test case as small and as simple as possible. But the weird thing is that if I remove any single field from the `User` data type then it decodes without any problems!

Please, send help 🆘

**Comment by gwils** [comment] 2018-11-22 06:34
That's really strange! I'll look into this.

**Comment by gwils** [comment] 2018-11-22 23:53
I can reproduce the bug. Thank you for the `#! /usr/bin/env cabal` script reproduction case. That's extremely helpful!

If I add or remove a character this works, so the problem seems to be with CSV files that are exactly 512 bytes long (probably also multiples of 512).

**Comment by ChShersh** [comment] 2018-11-23 02:34
@gwils Thank you for working on this! Such errors might be really hard to spot.

**Comment by gwils** [comment] 2018-11-23 05:49
Fixed by https://github.com/haskell-works/hw-dsv/pull/46

Run `cabal update` and it should work :)

**Closed by gwils** 2018-11-23 05:49 UTC
